# Generated by Django 4.2.3 on 2023-08-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_remove_subgenre_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgenre',
            name='parent_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manga.genre', unique=True),
        ),
    ]
