# Generated by Django 4.2.3 on 2023-08-12 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_alter_subgenre_parent_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgenre',
            name='parent_genre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manga.genre'),
        ),
    ]
